//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeeMensa.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SeeMensa.Language.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to canteen.
        /// </summary>
        public static string AppBarMensaInfo {
            get {
                return ResourceManager.GetString("AppBarMensaInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to refresh.
        /// </summary>
        public static string AppBarRefresh {
            get {
                return ResourceManager.GetString("AppBarRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seeMENSA for Windows 8.
        /// </summary>
        public static string AppBarWin8 {
            get {
                return ResourceManager.GetString("AppBarWin8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by B. Sautermeister &amp; P. Mutter.
        /// </summary>
        public static string ApplicationAuthor {
            get {
                return ResourceManager.GetString("ApplicationAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seeMENSA gives you the opportunity to view the current meals of your canteen around Lake Constance..
        /// </summary>
        public static string ApplicationDescription {
            get {
                return ResourceManager.GetString("ApplicationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seeMENSA.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canteen.
        /// </summary>
        public static string Canteen {
            get {
                return ResourceManager.GetString("Canteen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to apps@bsautermeister.de.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// </summary>
        public static string Employee {
            get {
                return ResourceManager.GetString("Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for Windows Phone.
        /// </summary>
        public static string ForWindowsPhone7 {
            get {
                return ResourceManager.GetString("ForWindowsPhone7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest.
        /// </summary>
        public static string Guest {
            get {
                return ResourceManager.GetString("Guest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have any further questions, ideas or problems with seeMENSA, please do not hesitate to contact us..
        /// </summary>
        public static string HelpText {
            get {
                return ResourceManager.GetString("HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string HelpTitle {
            get {
                return ResourceManager.GetString("HelpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string InAppStoreLoading {
            get {
                return ResourceManager.GetString("InAppStoreLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are currently no in-app purchases available. Please try again later..
        /// </summary>
        public static string InAppStoreNoProducts {
            get {
                return ResourceManager.GetString("InAppStoreNoProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to purchased.
        /// </summary>
        public static string InAppStorePurchased {
            get {
                return ResourceManager.GetString("InAppStorePurchased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In-App Store.
        /// </summary>
        public static string InAppStoreTitle {
            get {
                return ResourceManager.GetString("InAppStoreTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canteen Friedrichshafen.
        /// </summary>
        public static string MensaFn {
            get {
                return ResourceManager.GetString("MensaFn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canteen HTWG Constance.
        /// </summary>
        public static string MensaHtwg {
            get {
                return ResourceManager.GetString("MensaHtwg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canteen Info.
        /// </summary>
        public static string MensaInfoTitle {
            get {
                return ResourceManager.GetString("MensaInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canteen plan.
        /// </summary>
        public static string MensaTile {
            get {
                return ResourceManager.GetString("MensaTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menseria University of Constance.
        /// </summary>
        public static string MensaUni {
            get {
                return ResourceManager.GetString("MensaUni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canteen HS/PH Weingarten.
        /// </summary>
        public static string MensaWg {
            get {
                return ResourceManager.GetString("MensaWg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention.
        /// </summary>
        public static string MessageBoxAttention {
            get {
                return ResourceManager.GetString("MessageBoxAttention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string MessageBoxInfo {
            get {
                return ResourceManager.GetString("MessageBoxInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Because we are moving to a new marketplace account is the reason why your installed seeMENSA will not get anymore updates. Additionally, this version will not work from 15th September because of different changes by Seezeit. You will have to redownload the adjusted version 1.5 of seeMENSA from marketplace. We try to finish the new version until start of WS 11/12. If you have further questions, please no not hesitate to contact us!.
        /// </summary>
        public static string MessageBoxNewMarketplaceText {
            get {
                return ResourceManager.GetString("MessageBoxNewMarketplaceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No information received. Please check your internet connection..
        /// </summary>
        public static string MessageBoxNoConnectivityText {
            get {
                return ResourceManager.GetString("MessageBoxNoConnectivityText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data of your selected canteen is currently not available..
        /// </summary>
        public static string MessageBoxNoDataText {
            get {
                return ResourceManager.GetString("MessageBoxNoDataText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is currently no canteen data available..
        /// </summary>
        public static string MessageBoxNoMensaText {
            get {
                return ResourceManager.GetString("MessageBoxNoMensaText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are currently no in-app purchases available. Please try again later..
        /// </summary>
        public static string MessageBoxNoProducts {
            get {
                return ResourceManager.GetString("MessageBoxNoProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to more apps.
        /// </summary>
        public static string MoreApps {
            get {
                return ResourceManager.GetString("MoreApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prices.
        /// </summary>
        public static string Prices {
            get {
                return ResourceManager.GetString("Prices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to privacy info.
        /// </summary>
        public static string PrivacyInfo {
            get {
                return ResourceManager.GetString("PrivacyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pupil.
        /// </summary>
        public static string Pupil {
            get {
                return ResourceManager.GetString("Pupil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rate and review.
        /// </summary>
        public static string RateAndReview {
            get {
                return ResourceManager.GetString("RateAndReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please tap here to review this App!.
        /// </summary>
        public static string Review {
            get {
                return ResourceManager.GetString("Review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student.
        /// </summary>
        public static string Student {
            get {
                return ResourceManager.GetString("Student", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to support and feedback.
        /// </summary>
        public static string SupportAndFeedback {
            get {
                return ResourceManager.GetString("SupportAndFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to updating....
        /// </summary>
        public static string UpdateStatusText {
            get {
                return ResourceManager.GetString("UpdateStatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
